export const userConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

  export const listConstants = {
    GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
    GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
    GET_ALL_USERS_SUCCESS:"GET_ALL_USERS_SUCCESS",
  }